name: Build and publish to Docker Hub

on:
  pull_request:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "shivjm/node-libvips"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 17, 18, 19]
        libvips: [8.14.1]
    env:
      IMAGE_TAG: "node${{ matrix.node }}-libvips${{ matrix.libvips }}"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get current date & time
        id: get-date
        run: |
          echo "DATETIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: "${{ github.event_name != 'pull_request' }}"
          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          build-args: |
            NODE_VERSION=${{ matrix.node }}
            LIBVIPS_VERSION=${{ matrix.libvips }}
          labels: |
            org.opencontainers.image.created=${{ steps.get-date.output.DATETIME }}
